package es.daw.thorvet.entity;


import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;

@Entity
@Setter
@Getter
@Table(name = "medical_services")
public class MedicalService {

//    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    code       VARCHAR(30)   NOT NULL,
//    name       VARCHAR(120)  NOT NULL,
//    base_price DECIMAL(12,2) NOT NULL,
//    active     BOOLEAN NOT NULL

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(length = 30, nullable = false)
    private String code;

    @Column(length = 120, nullable = false)
    private String name;

    @Column(name = "base_price", precision = 12, scale = 2, nullable = false)
    private BigDecimal basePrice;

    @Column(nullable = false)
    private boolean active;
}
