spring.application.name=Thorvet


server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/thorvet
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never


spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.sql.init.encoding=UTF-8

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.messages.encoding=UTF-8

jwt.secret=${JWT_SECRET:kHsfLMNQRuuHc9wRu53S3IQN+dbxEbedyN49XGebWsA=}
jwt.expiration=${JWT_EXPIRATION:2}

logging.level.org.springframework.security=DEBUG