spring.application.name=Thorvet


server.port=8083

spring.datasource.url=jdbc:h2:mem:clinica-db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.sql.init.encoding=UTF-8

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.messages.encoding=UTF-8

jwt.secret=${JWT_SECRET:kHsfLMNQRuuHc9wRu53S3IQN+dbxEbedyN49XGebWsA=}
jwt.expiration=${JWT_EXPIRATION:2}

logging.level.org.springframework.security=DEBUG