-- =========================
--  VET CLINIC API - SCHEMA H2
-- =========================

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS app_users;
DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS invoice_lines;
DROP TABLE IF EXISTS invoices;

DROP TABLE IF EXISTS appointments;

DROP TABLE IF EXISTS vet_specialties;

DROP TABLE IF EXISTS medical_services;
DROP TABLE IF EXISTS vets;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS owners;

-- -------------------------
-- OWNERS (Propietarios)
-- -------------------------
CREATE TABLE owners (
                        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        dni      VARCHAR(20)  NOT NULL,
                        full_name VARCHAR(120) NOT NULL,
                        email    VARCHAR(150) NOT NULL,
                        phone    VARCHAR(30),
                        address  VARCHAR(250),
                        active   BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_owner_dni ON owners(dni);

-- -------------------------
-- PATIENTS (Mascotas)
-- -------------------------
CREATE TABLE patients (
                          id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          chip_number   VARCHAR(20)  NOT NULL,
                          name          VARCHAR(80)  NOT NULL,
                          species       VARCHAR(20)  NOT NULL,   -- CANINE, FELINE, RABBIT, BIRD, EXOTIC
                          breed         VARCHAR(80),
                          date_of_birth DATE,
                          weight_kg     DECIMAL(6,2),
                          owner_id      BIGINT NOT NULL,
                          active        BOOLEAN NOT NULL,

                          CONSTRAINT fk_patients_owner
                              FOREIGN KEY (owner_id) REFERENCES owners(id)
);

CREATE UNIQUE INDEX uk_patient_chip ON patients(chip_number);
CREATE INDEX idx_patient_owner ON patients(owner_id);

-- -------------------------
-- VETS (Veterinarios)
-- -------------------------
CREATE TABLE vets (
                      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      license_number VARCHAR(40)  NOT NULL,
                      full_name      VARCHAR(120) NOT NULL,
                      email          VARCHAR(150) NOT NULL,
                      active         BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_vet_license ON vets(license_number);

-- -------------------------
-- MEDICAL SERVICES (Servicios veterinarios)
-- -------------------------
CREATE TABLE medical_services (
                                  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  code       VARCHAR(30)   NOT NULL,
                                  name       VARCHAR(120)  NOT NULL,
                                  base_price DECIMAL(12,2) NOT NULL,
                                  active     BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_medical_service_code ON medical_services(code);

-- -------------------------
-- VET_SPECIALTIES
-- PK compuesta: (vet_id, specialty)
-- -------------------------
CREATE TABLE vet_specialties (
                                 vet_id                   BIGINT NOT NULL,
                                 specialty                VARCHAR(30) NOT NULL,
                                 level                    VARCHAR(20) NOT NULL,
                                 active                   BOOLEAN NOT NULL,
                                 since_date               DATE NOT NULL,
                                 consultation_fee_override DECIMAL(12,2),

                                 CONSTRAINT pk_vet_specialties PRIMARY KEY (vet_id, specialty),
                                 CONSTRAINT fk_vet_specialties_vet
                                     FOREIGN KEY (vet_id) REFERENCES vets(id)
);

-- -------------------------
-- APPOINTMENTS (Citas)
-- -------------------------
CREATE TABLE appointments (
                              id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              patient_id          BIGINT NOT NULL,
                              vet_id              BIGINT NOT NULL,
                              start_at            TIMESTAMP NOT NULL,
                              end_at              TIMESTAMP NOT NULL,
                              minutes             INT NOT NULL,
                              status              VARCHAR(20) NOT NULL,   -- SCHEDULED, COMPLETED, CANCELLED, NO_SHOW
                              reason              VARCHAR(250),
                              cancellation_reason VARCHAR(250),

                              CONSTRAINT fk_appointments_patient
                                  FOREIGN KEY (patient_id) REFERENCES patients(id),
                              CONSTRAINT fk_appointments_vet
                                  FOREIGN KEY (vet_id) REFERENCES vets(id)
);

CREATE INDEX idx_appointment_vet_start     ON appointments(vet_id, start_at);
CREATE INDEX idx_appointment_patient_start ON appointments(patient_id, start_at);

-- -------------------------
-- INVOICES (1-1 con appointment)
-- -------------------------
CREATE TABLE invoices (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          appointment_id BIGINT        NOT NULL,
                          status         VARCHAR(20)   NOT NULL,   -- ISSUED, PAID, CANCELLED
                          subtotal       DECIMAL(12,2) NOT NULL,
                          tax_total      DECIMAL(12,2) NOT NULL,
                          total          DECIMAL(12,2) NOT NULL,
                          issued_at      TIMESTAMP,
                          paid_at        TIMESTAMP,
                          payment_method VARCHAR(20),             -- CARD, CASH, TRANSFER

                          CONSTRAINT uk_invoices_appointment UNIQUE (appointment_id),
                          CONSTRAINT fk_invoices_appointment
                              FOREIGN KEY (appointment_id) REFERENCES appointments(id)
);

-- -------------------------
-- INVOICE_LINES
-- -------------------------
CREATE TABLE invoice_lines (
                               id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               invoice_id     BIGINT        NOT NULL,
                               service_id     BIGINT        NOT NULL,
                               quantity       INT           NOT NULL,
                               unit_price     DECIMAL(12,2) NOT NULL,
                               vat_rate       VARCHAR(10)   NOT NULL,   -- VAT_21, VAT_10, VAT_0
                               discount_type  VARCHAR(10)   NOT NULL,   -- NONE, PERCENT, FIXED
                               discount_value DECIMAL(12,2),
                               line_total     DECIMAL(12,2) NOT NULL,

                               CONSTRAINT fk_invoice_lines_invoice
                                   FOREIGN KEY (invoice_id) REFERENCES invoices(id),
                               CONSTRAINT fk_invoice_lines_service
                                   FOREIGN KEY (service_id) REFERENCES medical_services(id)
);

CREATE INDEX idx_invoice_lines_invoice ON invoice_lines(invoice_id);

-- -------------------------
-- SECURITY TABLES
-- -------------------------
CREATE TABLE roles (
                       id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(40) NOT NULL
);

CREATE UNIQUE INDEX uk_roles_name ON roles(name);

CREATE TABLE app_users (
                           id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           username VARCHAR(60)  NOT NULL,
                           password VARCHAR(100) NOT NULL,
                           enabled  BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_users_username ON app_users(username);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,

                            CONSTRAINT pk_user_roles  PRIMARY KEY (user_id, role_id),
                            CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_users(id),
                            CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);