package es.daw.thorvet.dto.medicalService;

import lombok.Builder;

import java.math.BigDecimal;

@Builder
public record MedicalServiceResponseDTO(
        Long id,
        String code,
        String name,
        BigDecimal base_price,
        Boolean active
) {
}


//    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    code       VARCHAR(30)   NOT NULL,
//    name       VARCHAR(120)  NOT NULL,
//    base_price DECIMAL(12,2) NOT NULL,
//    active     BOOLEAN NOT NULL